/**
 * contracts — src/v1/index.ts
 */

export {
  type CanonicalEvent,
  hashPayload,
  canonicalizeJson,
  assertCanonicalEvent,
  serializeCanonicalEvent,
  parseCanonicalEvent,
} from './canonical-event.js';

export {
  type Capability,
  type Cursor,
  type ObjectRef,
  type SourceObject,
  type SourceColumn,
  type SourceSchema,
  type HealthState,
  type HealthStatus,
  type WriteBackRequest,
  type WriteBackResult,
  type PushdownOp,
  type PushdownPredicate,
  type PushdownSpec,
  type FederatedRowAcl,
  type FederatedRow,
  type FederatedQueryResult,
  type Connector,
} from './connector.js';

export {
  type DatasetId,
  type VersionId,
  type DatasetDef,
  type Dataset,
  type CommitInput,
  type DatasetVersion,
  type VersionDiff,
  type DatasetStore,
  assertCommitInput,
  buildGoldenCommitInput,
} from './dataset-store.js';

export {
  type DeltaKind,
  type DeltaRef,
  type DeltaOp,
  type IndividualDelta,
  type CombinedDelta,
  type BaseSnapshot,
  type MinimalDeltaSet,
  buildGoldenDeltaOps,
} from './delta-tree.js';

export {
  type LogicalTimestamp,
  type RowId,
  type TxStatus,
  type SnapshotRequest,
  type SnapshotResult,
  type ReplayResult,
  type TimeTravelStore,
  buildGoldenSnapshotRequest,
} from './time-travel.js';

export {
  type IncrementalStatus,
  type IncrementalComputability,
  type TransformOpKind,
  type TransformStep,
  type TransformProgram,
  type TransformRunResult,
  buildGoldenTransformStep,
} from './transform.js';

export {
  type DatasetKind,
  type BuildStatus,
  type DependencyKind,
  type PipelineDatasetDef,
  type PipelineEdge,
  type BuildJobSpec,
  type ScheduleTickResult,
  type DatasetAsset,
  type SensorKind,
  type SensorDef,
  buildGoldenPipelineEdge,
} from './pipeline-dag.js';

export {
  type QualityDimension,
  type RuleSeverity,
  type RuleActionKind,
  type QualityRule,
  type RuleCondition,
  type QualityScore,
  type QualityReport,
  type QuarantineRecord,
  type CompositeDatasetDef,
  buildGoldenQualityRule,
} from './data-quality.js';

export {
  type SandboxDenyReason,
  type SandboxPolicy,
  type SandboxIdentity,
  type SandboxAuditEvent,
  type SandboxRunResult,
  buildGoldenSandboxPolicy,
} from './sandbox.js';

export {
  type PipelineRunId,
  type DerivationProgramId,
  type LineageVersionKind,
  type PipelineRun,
  type LineageEdge,
  type LineageVersionNode,
  type CompoundLineageNode,
  type ProvenanceGraph,
  type LineageCompletenessReport,
  type LineageChangeEvent,
  type RegisterRawVersionInput,
  type RecordPipelineRunInput,
  type LineageStore,
  buildGoldenPipelineRun,
  assertPipelineRun,
} from './lineage.js';

export {
  type ColumnRef,
  type ColumnLineageEdge,
  type ColumnMarking,
  type ColumnMapping,
  type RecordColumnMappingsInput,
  type ColumnLineageStore,
  columnRefKey,
  parseColumnRefKey,
  buildGoldenColumnLineageEdge,
  assertColumnRef,
  assertColumnLineageEdge,
} from './column-lineage.js';

export {
  type ClassificationName,
  type ClassificationLevel,
  type ClassificationPrincipal,
  type ClassifiedItem,
  type DisseminationView,
  UNCLASSIFIED,
  CONFIDENTIAL,
  SECRET,
  TOP_SECRET,
  DEFAULT_CLASSIFICATION_HIERARCHY,
  classificationByName,
  resolveClassification,
  maxClassification,
  minClassification,
  commonViewingLevel,
  canViewAtLevel,
  effectiveViewingLevel,
  disseminationView,
  inheritClassification,
  sharingConstraint,
  classificationPolicyTag,
  classificationFromPolicyTags,
  assertClassificationLevel,
} from './classification.js';

export {
  type PrincipalId,
  type Epid,
  type PolicyNodeId,
  type ResourceId,
  type PolicyOperation,
  type AuthzDecision,
  type NodePolicyId,
  type AuthzContext,
  type AuthorizeRequest,
  type AuthorizeResult,
  type SecurityMatrixCell,
  type SecurityMatrix,
  type PolicyNode,
  type ResourcePermissions,
  type ResourceCreateSpec,
  type ResourceCreateResult,
  type PolicyEngine,
  buildGoldenAuthorizeRequest,
  assertAuthorizeResult,
  isReadOperation,
  allowsMutation,
  allowsRead,
  authorizeProceeds,
} from './policy.js';

export {
  NONINTERFERENCE_CHANNELS,
  type NoninterferenceChannel,
  type HiddenMiss,
  HIDDEN_MISS,
  type ChannelObservation,
  type ProbeResult,
  type NoninterferenceReport,
  type AuthzFuzzCase,
  type AuthzFuzzViolation,
  type AuthzFuzzReport,
  assertHiddenMiss,
  fingerprintsEqual,
} from './noninterference.js';

export {
  type AuditEntryId,
  type AuditMessageType,
  type AuditEntry,
  type AuditVerifyResult,
  type AuditAppendInput,
  type AuditRepository,
  type AuditLog,
  buildGoldenAuditEntry,
} from './audit.js';

export {
  type SqlQueryResult,
  type SqlClient,
  type TransactionManager,
} from './sql.js';

export {
  type OutboxInsertInput,
  type OutboxReader,
  type OutboxRepository,
  type OutboxRequest,
  type OutboxDispatchStatus,
  type OutboxDispatchRecord,
  type OutboxDispatcher,
} from './outbox.js';

export {
  type OntologyId,
  type OntologyVersionId,
  type ObjectTypeId,
  type PropertyTypeId,
  type LinkTypeId,
  type ActionTypeId,
  type FunctionTypeId,
  type OntologyLayer,
  type PropertyBaseType,
  type PropertyValidator,
  type PropertyComponent,
  type PropertyTypeDef,
  type ObjectTypeDef,
  type LinkTypeDef,
  type ActionTypeStatus,
  type ActionParameterDef,
  type ActionSubmissionCriterion,
  type ActionRule,
  type ActionSideEffect,
  type ActionTypeDef,
  type FunctionTypeDef,
  type OntologyVersion,
  type Ontology,
  type OntologyDraft,
  type CreateOntologyInput,
  type CommitOntologyInput,
  type OntologyRegistry,
  type OntologyDiff,
  buildGoldenObjectType,
  assertObjectTypeDef,
} from './ontology.js';

export {
  type ActionParameterSchemaError,
  type SafePattern,
  compilePattern,
  hasNestedQuantifiers,
  validateParameterDef,
  validateActionTypeDefSchema,
} from './action-parameter-schema.js';

export {
  type ObjectSetOp,
  type PropertyValue,
  type ObjectSetFilter,
  type BaseObjectSet,
  type FilterObjectSet,
  type UnionObjectSet,
  type IntersectObjectSet,
  type SubtractObjectSet,
  type StaticObjectSet,
  type SearchAroundObjectSet,
  type ObjectSet,
  type AggregationKind,
  type ObjectSetAggregation,
  type ObjectSetLoadRequest,
  type ObjectSetAggregateRequest,
} from './object-set.js';

export {
  type SearchBackend,
  type SearchSurface,
  type SearchDocument,
  type SearchPrincipal,
  type SearchAroundSpec,
  type FederateSpec,
  type SearchQuery,
  type SearchHit,
  type SearchFacetValue,
  type SearchFacet,
  type SearchSuggestion,
  type SearchResponse,
  type SearchTemplate,
  type SearchLink,
  buildGoldenSearchDocument,
  assertSearchQuery,
  assertSearchDocument,
} from './search.js';

export {
  type ObjectRecordId,
  type LinkRecordId,
  type ObjectRecord,
  type CreateObjectInput,
  type UpdateObjectInput,
  type DeleteObjectInput,
  type ListObjectsOptions,
  type LinkRecord,
  type CreateLinkInput,
  type DeleteLinkInput,
  type ListLinksOptions,
  type ObjectRepository,
  type ObjectReader,
  type ObjectWriter,
  type LinkRepository,
  type LinkReader,
  type LinkWriter,
  urnOf,
} from './object-repository.js';

export {
  type ProjectionOperation,
  type ProjectionStatus,
  type ProjectObjectCommand,
  type DeleteProjectedObjectCommand,
  type ProjectLinkCommand,
  type DeleteProjectedLinkCommand,
  type ProjectionResult,
  type ProjectionEffect,
  type ProjectionBatchCommand,
  type ProjectionBatchResult,
  type ProjectionWriter,
  type MigrateObjectCommand,
} from './projection.js';

export {
  type IngestionRunId,
  type IngestionQuarantineId,
  type IngestionRunKind,
  type IngestionRunStatus,
  type ConnectorKind,
  type ConnectorRegistration,
  type ConnectorRegistrationRepository,
  type PublishMappingInput,
  type MappingVersionRepository,
  type RawEnvelope,
  type ConnectorPage,
  type MappingDefinition,
  type IngestionMappingPin,
  type EnqueueWebhookInput,
  type IngestionWebhookResult,
  type StartPullInput,
  type RetryQuarantineInput,
  type IngestionRun,
  type IngestionQuarantineEntry,
  type IngestionRuntime,
  definitionOf,
  pinFromMappingVersion,
  envelopeFromCanonical,
  assertRawEnvelope,
  assertMappingDefinition,
  assertIngestionMappingPin,
} from './ingestion.js';

export {
  type OperationalEventId,
  type OperationalEventKind,
  type OperationalEvent,
  type OperationalEventStore,
} from './operational-event.js';

export {
  type ActionExecutionId,
  type ActionExecutionStatus,
  type ActionValidateRequest,
  type ActionValidateResult,
  type ActionApplyRequest,
  type ActionApplyResult,
  type ActionExecution,
  type ActionExecutionClaimResult,
  type ActionExecutionStore,
  type ResolvedActionDefinition,
  type ActionDefinitionResolver,
  type ActionExecutor,
  type ActionParameterNode,
  type ActionParameterTree,
  type ActionWorkflowStep,
  type ActionWorkflowDef,
  type ActionWorkflowApplyRequest,
  type ActionWorkflowApplyResult,
} from './action-runtime.js';

export {
  type FunctionId,
  type FunctionVersion,
  type FunctionOutputKind,
  type FunctionObjectInput,
  type FunctionDef,
  type FunctionImpl,
  type FunctionInvokeRequest,
  type FunctionInvokeResult,
  type FunctionRegistry,
  type FunctionExecutionPin,
  type FunctionExecutionStatus,
  type FunctionFailureCode,
  type FunctionObjectRef,
  type FunctionActionInvocation,
  type FunctionTypedError,
  type FunctionExecution,
  type FunctionCreateRequest,
  type FunctionArtifact,
  type FunctionArtifactStore,
  type FunctionDefinitionResolver,
  type FunctionRuntime,
  buildGoldenFunctionDef,
  assertFunctionDef,
  assertFunctionExecutionPin,
  isFunctionTerminal,
  FUNCTION_SHA256,
  FUNCTION_TERMINAL_STATUSES,
} from './function-runtime.js';

export {
  type MappingId,
  type MappingVersionId,
  type OntologyObjectId,
  type ObjectHistoryId,
  type LinkInstanceId,
  type ProjectionRunId,
  type SourceField,
  type ObjectChangeSource,
  type PropertyMapping,
  type LinkMapping,
  type MappingVersion,
  type DatasetObjectMapping,
  type MappingDraft,
  type CreateMappingInput,
  type CommitMappingInput,
  type OntologyObject,
  type ObjectHistoryEntry,
  type ObjectProvenance,
  type LinkInstance,
  type ObjectQuery,
  type DatasetRow,
  type ProjectInput,
  type ProjectResult,
  type AuthorizeFn,
  type ObjectPlatform,
  buildGoldenPropertyMapping,
  assertMappingVersion,
} from './object-platform.js';

export {
  type GraphObjectId,
  type TicketId,
  type LinkMigrationId,
  type TraverseDirection,
  type GraphObject,
  type TypedLink,
  type LinkMaterializeSpec,
  type TraverseHop,
  type TraverseQuery,
  type TraverseResult,
  type IntegrityIssue,
  type IntegrityReport,
  type LinkMigrationInput,
  type LinkMigrationResult,
  type RemoteObjectRef,
  type KnowledgeGraphStore,
  buildGoldenTypedLink,
  assertTypedLink,
} from './knowledge-graph.js';

export {
  type RedactionCriterionKind,
  type RedactionCriterion,
  type RedactionRequest,
  type RedactedProperty,
  type SanitizedGraph,
  buildGoldenRedactionCriterion,
  assertRedactionRequest,
  assertSanitizedGraph,
} from './graph-redaction.js';

export {
  type EntityRecordId,
  type ResolutionRunId,
  type RuleVersionId,
  type ClusterId,
  type BlockKey,
  type MatchAuditId,
  type CanonicalEntityId,
  type SourceCanonicalLinkId,
  type MergeEventId,
  type GoldSetId,
  type GoldPairId,
  type MatchDecision,
  type MatchingTechnique,
  type ReviewDecision,
  type GoldLabel,
  type CanonicalLinkStatus,
  type MergeEventKind,
  type EntityRecord,
  type NormalizedFields,
  type NormalizedRecord,
  type LinkingTerm,
  type ResolutionCriteria,
  type ScoreFeatures,
  type CandidatePair,
  type SoftCluster,
  type ResolutionStats,
  type ResolutionResult,
  type RunResolutionInput,
  type MatchReview,
  type MatchAuditEntry,
  type SourceCanonicalLink,
  type CanonicalEntity,
  type MergeEvent,
  type MergeCanonicalInput,
  type UnmergeInput,
  type RecordReviewInput,
  type GoldPair,
  type GoldSet,
  type UpsertGoldPairInput,
  type ErMetrics,
  type ReviewQueueItem,
  type ApplyFeedbackResult,
  type SubmitReviewResult,
  type EntityFingerprintPoint,
  type FingerprintMatch,
  type ClusterScoringMetric,
  type ClusterScoringStrategy,
  type RankedCluster,
  type EntityResolutionEngine,
  GOLD_SET_TARGET_SIZE,
  buildGoldenEntityRecord,
  buildGoldenCriteria,
  buildGoldenClusterScoringStrategy,
  assertEntityRecord,
  assertResolutionCriteria,
  assertMatchAuditEntry,
  assertCanonicalEntity,
  assertGoldPair,
  goldLabelFromReview,
} from './entity-resolution.js';

export {
  type FederatedProvenance,
  type FederatedViewKind,
  type AclLevel,
  type AclEntry,
  type AccessControlProperties,
  type FederationPrincipal,
  type DataFragment,
  type FederatedLink,
  type PromotionMetadata,
  type TemporaryObject,
  type PlatformObject,
  type FederatedView,
  type FederatedPromotion,
  type FederatedScript,
  type FederationQuery,
  type FederationSourceCatalogEntry,
  type FederationPlan,
  buildGoldenPushdownSpec,
  buildGoldenTemporaryObject,
  assertPushdownSpec,
  assertTemporaryObject,
  isTemporaryObject,
  isPlatformObject,
} from './federation.js';

export {
  type EdgeSourceKind,
  EDGE_SOURCE_KINDS,
  type EdgeOperator,
  type EdgeSourceAccessPattern,
  type BaselineProfile,
  type ActivityUnit,
  type AnomalySeverity,
  type ActivityAnomaly,
  type BaselineProfileDisplay,
  type ActivityDetailedView,
  type TransmissionKind,
  type DigitalTransmission,
  type DashboardActivityRow,
  type ActivityDashboardView,
  buildGoldenActivityUnit,
  assertActivityUnit,
  isEdgeSourceKind,
} from './edge.js';

export {
  type ReplicaId,
  type ObjectId as OfflineObjectId,
  type LinkSetId,
  type InvestigationId,
  type ChangeSetId,
  type VersionVector,
  type VersionCompare,
  type ReplicaObject,
  type ReplicaLink,
  type ReplicaLinkSet,
  type ReplicaUpdateKind,
  type ReplicaUpdate,
  type ApplyStatus,
  type DataConflictType,
  DATA_CONFLICT_TYPES,
  type TitleSubType,
  TITLE_SUB_TYPES,
  type GeotimeSubType,
  GEOTIME_SUB_TYPES,
  GEOTIME_PROPERTY_KEYS,
  type AmbiguousDataConflict,
  type ConflictGroup,
  type ConflictResolution,
  type ConflictFilterView,
  type ConflictResolutionView,
  type ChangeOperation,
  type ChangeRecord,
  type ChangeSet,
  type Investigation,
  type BaseFile,
  type DiscoFile,
  isDataConflictType,
  buildGoldenReplicaObject,
  buildGoldenVersionVector,
  assertVersionVector,
  assertReplicaObject,
  objectVisibleTo,
  canonicalAuthorizedState,
} from './offline.js';

export {
  type ReplicationOperation,
  REPLICATION_OPERATIONS,
  type ReplicationPolicy,
  type ReplicationMutation,
  type VectorCheckpoint,
  type ReplicationChunkSpec,
  type ReplicationPlan,
  type ReplicationChunk,
  type OntologyTypeKind,
  type OntologyMapSpec,
  buildGoldenReplicationMutation,
  buildGoldenOntologyMapSpec,
  assertReplicationMutation,
  isReplicationOperation,
} from './replication.js';

export {
  type GraphMatchOperator,
  type GraphPropertyMatch,
  type GraphPatternNode,
  type GraphPatternEdge,
  type GraphPatternBranch,
  type GraphPattern,
  type GraphPatternBinding,
  type GraphPatternMatch,
  type GraphPatternResult,
  type InvestigationBlockStrategy,
  type TokenTransform,
  type InvestigationIndexHit,
  type InvestigationSearchResult,
  type ExploreMetric,
  type ExploreMetricSelection,
  type ExploreObjectScore,
  type ExploreScoreResult,
  type ObjectSlot,
  type BindingEvalResult,
  type ExplorePrincipal,
  buildGoldenGraphPattern,
  assertGraphPattern,
} from './explore.js';

export {
  assertAipAskRequest,
  assertAipAgentRunRequest,
  type AipRiskLevel,
  type ObjectCitation,
  type AipAskRequest,
  type AipAskResponse,
  type AipToolDefinition,
  type LlmMessageRole,
  type LlmMessage,
  type LlmToolCall,
  type LlmCompletionRequest,
  type LlmCompletionResult,
  type LlmProvider,
  type AipObjectReader,
  type AipActionPort,
  type AipAgentStateId,
  type AipAgentStateStep,
  type AipAgentRunRequest,
  type AipAgentRunResponse,
  type AipProfile,
} from './aip.js';

export {
  AIP_ADVERSARIAL_KINDS,
  assertAipEvalCase,
  type AipAdversarialKind,
  type AipEvalMode,
  type AipEvalExpectedAction,
  type AipEvalRubric,
  type AipEvalCase,
  type AipEvalMetrics,
  type AipEvalCaseResult,
  type AipEvalSuiteResult,
} from './aip-eval.js';
